<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\File;

class ExportSchemaCommand extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'app:export-schema';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Export database schema (structure only) to a SQL file';

    /**
     * Execute the console command.
     */
    public function handle()
    {
        $this->info('Starting schema export...');

        if (config('database.default') !== 'pgsql') {
            $this->error('This manual Schema Extractor is optimized for PostgreSQL databases.');
            return;
        }

        $connection = DB::connection();

        // 1. Get all base tables in public schema
        $tables = $connection->select("SELECT table_name FROM information_schema.tables WHERE table_schema = 'public' AND table_type = 'BASE TABLE'");

        $sql = "-- Schema export generated by app:export-schema\n";
        $sql .= "-- For a 100% exact 'Golden Template' (with complex triggers, indices, etc.), running `pg_dump --schema-only` is recommended.\n\n";

        foreach ($tables as $table) {
            $tableName = $table->table_name;
            $this->info("Exporting table schema: $tableName");

            $sql .= "-- ---------------------------------------------------------\n";
            $sql .= "-- Table structure for `$tableName`\n";
            $sql .= "-- ---------------------------------------------------------\n\n";
            $sql .= "CREATE TABLE \"$tableName\" (\n";

            // Get columns and definitions
            $columns = $connection->select("
                SELECT column_name, data_type, character_maximum_length, column_default, is_nullable
                FROM information_schema.columns 
                WHERE table_name = ?
                ORDER BY ordinal_position
            ", [$tableName]);

            $colDefs = [];
            foreach ($columns as $column) {
                // Formatting data types slightly
                $type = $column->data_type;
                if ($type === 'character varying' && $column->character_maximum_length) {
                    $type .= '(' . $column->character_maximum_length . ')';
                }

                $def = '    "' . $column->column_name . '" ' . $type;

                if ($column->column_default !== null) {
                    $def .= ' DEFAULT ' . $column->column_default;
                }

                if ($column->is_nullable === 'NO') {
                    $def .= ' NOT NULL';
                }

                $colDefs[] = $def;
            }

            // Get Primary Keys
            $pks = $connection->select("
                SELECT a.attname
                FROM   pg_index i
                JOIN   pg_attribute a ON a.attrelid = i.indrelid AND a.attnum = ANY(i.indkey)
                WHERE  i.indrelid = ?::regclass AND i.indisprimary;
            ", [$tableName]);

            if (!empty($pks)) {
                $pkColumns = array_map(function ($pk) {
                    return '"' . $pk->attname . '"'; }, $pks);
                $colDefs[] = '    PRIMARY KEY (' . implode(', ', $pkColumns) . ')';
            }

            $sql .= implode(",\n", $colDefs) . "\n);\n\n";
        }

        $path = database_path('schema_only_export.sql');
        File::put($path, $sql);

        $this->info("Schema export completed successfully!");
        $this->info("Saved Golden Template to: $path");
    }
}
